apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: snankaninodejsapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: snankaninodejsapp 
    spec:
      containers:
        - name: snankaninodejsapp 
          image: atbaggaacr.azurecr.io/snankaninodejsapp 
          ports:
          - containerPort: 8080